server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_educational_institution?createDatabaseIfNotExist=true
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          lob:
            non-contextual_creation: true
  security:
    oauth2:
      client:
        registration:
          local:
            client-id: awuser
            client-secret: 123456
        provider:
          local:
            issuer-uri: http://localhost:8081
aw:
  auth:
    provider-uri: "http://localhost:8081"
    jks:
      keypass: 123456
      storepass: 123456
      alias: awblog
      path: keystore/awblog.jks


